---

# Requires EPEL repo
- name: (znc_install) [1/6] ZNC is installed and the latest version
  package:
    name: znc
    state: latest

- name: (znc_install) [2/6] ZNC is enabled on boot
  service:
    name: znc
    enabled: yes

- name: (znc_install) [3/6] Config dir is present
  file:
    path: /var/lib/znc/.znc/configs
    state: directory
    owner: znc
    group: znc
    mode: 0740

- name: (znc_install) [4/6] New self-signed SSL cert/key pair is generated and deployed
  command: openssl req -x509 -newkey rsa:2048 -nodes -subj "{{ httpd_ssl_cert_subj_string }}" -days 3650 -keyout /var/lib/znc/.znc/key.pem -out /var/lib/znc/.znc/cert.pem
  args:
    creates: /var/lib/znc/.znc/key.pem
  register: new_key

- name: (znc_install) [5/6] Key Concatenated into Pem
  shell: "cat /var/lib/znc/.znc/key.pem > /var/lib/znc/.znc/znc.pem"
  when: new_key|succeeded

- name: (znc_install) [6/6] Cert Concatenated into Pem
  shell: "cat /var/lib/znc/.znc/cert.pem >> /var/lib/znc/.znc/znc.pem"
  when: new_key|succeeded
