---

# Requires EPEL repo
- name: ZNC is installed and the latest version
  package:
    name: znc
    state: latest

- name: ZNC is enabled on boot
  service:
    name: znc
    enabled: yes

- name: Config dir is present
  file:
    path: /var/lib/znc/.znc/configs
    state: directory
    owner: znc
    group: znc
    mode: 0740

- name: New self-signed SSL cert/key pair is generated and deployed
  command: openssl req -x509 -newkey rsa:2048 -nodes -subj "{{ httpd_ssl_cert_subj_string }}" -days 3650 -keyout /var/lib/znc/.znc/key.pem -out /var/lib/znc/.znc/cert.pem
  args:
    creates: /var/lib/znc/.znc/key.pem

- name: ZNC Pem is created step1
  shell: "cat /var/lib/znc/.znc/key.pem > /var/lib/znc/.znc/znc.pem"

- name: ZNC Pem is created step1
  shell: "cat /var/lib/znc/.znc/cert.pem >> /var/lib/znc/.znc/znc.pem"
